[build]
  command = "pnpm install && pnpm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.18.0"
  PNPM_VERSION = "9.9.0"
  NEXT_TELEMETRY_DISABLED = "1"
  # Configure secrets scanning to ignore Next.js build artifacts
  # These contain intentionally public environment variables
  SECRETS_SCAN_OMIT_PATHS = ".next/cache/**,.next/server/**,.next/standalone/**,.netlify/.next/**,.netlify/functions-internal/**"
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_SUPABASE_URL,NEXT_PUBLIC_SUPABASE_ANON_KEY,NEXT_PUBLIC_SITE_URL,NEXT_PUBLIC_DEV_SUPABASE_REDIRECT_URL"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

# Let the Next.js plugin handle routing; no manual redirects needed

